// GENERATED by scripts/generate-tokens.mjs from css/tokens.css — do not edit.
// Run `npm run tokens` after changing tokens.css.
//
// Keys are the CSS custom property name without the leading `--`, verbatim, so
// what you read here is greppable against the stylesheet.

/** @type {Record<string, string>} */
export const light = {
  "paper": "#faf9f7",
  "paper-2": "#f2f0ec",
  "ink": "#1c1a17",
  "ink-2": "#4f4a43",
  "ink-3": "#6f6860",
  "accent": "#a8232a",
  "accent-deep": "#7d1a1f",
  "link-hover": "#c22b33",
  "violet": "#8a7f74",
  "line": "#e4e0d9",
  "card": "#ffffff",
  "dark-panel": "#1c1a17",
  "font-display": "\"Fraunces\", Georgia, serif",
  "font-body": "\"Public Sans\", system-ui, sans-serif",
  "font-mono": "\"JetBrains Mono\", ui-monospace, monospace",
  "w-max": "1240px",
  "w-prose": "720px",
  "radius": "10px",
  "radius-btn": "3px",
  "ease-out": "cubic-bezier(0.22, 1, 0.36, 1)",
  "ease-in-out": "cubic-bezier(0.65, 0, 0.35, 1)",
  "dur-1": "0.16s",
  "dur-2": "0.28s",
  "dur-3": "0.62s",
  "accent-btn": "#a8232a",
  "accent-btn-hover": "#7d1a1f",
  "od-heading": "#ffffff",
  "od-fg": "#eeeae2",
  "od-fg-2": "#d8d2c6",
  "od-fg-3": "#c9c2b4",
  "od-muted": "#9c9488",
  "od-muted-2": "#b0a89a",
  "od-accent": "#e8897a",
  "od-accent-2": "#ffa693"
};

/** @type {Record<string, string>} */
export const dark = {
  "paper": "#191714",
  "paper-2": "#211f1b",
  "ink": "#eeeae2",
  "ink-2": "#c3bcb0",
  "ink-3": "#9c9488",
  "accent": "#d9483c",
  "accent-deep": "#e8897a",
  "link-hover": "#ffa693",
  "violet": "#7a7167",
  "line": "#37332c",
  "card": "#1d1b17",
  "dark-panel": "#121110",
  "font-display": "\"Fraunces\", Georgia, serif",
  "font-body": "\"Public Sans\", system-ui, sans-serif",
  "font-mono": "\"JetBrains Mono\", ui-monospace, monospace",
  "w-max": "1240px",
  "w-prose": "720px",
  "radius": "10px",
  "radius-btn": "3px",
  "ease-out": "cubic-bezier(0.22, 1, 0.36, 1)",
  "ease-in-out": "cubic-bezier(0.65, 0, 0.35, 1)",
  "dur-1": "0.16s",
  "dur-2": "0.28s",
  "dur-3": "0.62s",
  "accent-btn": "#c02f2a",
  "accent-btn-hover": "#a8232a",
  "od-heading": "#ffffff",
  "od-fg": "#eeeae2",
  "od-fg-2": "#d8d2c6",
  "od-fg-3": "#c9c2b4",
  "od-muted": "#9c9488",
  "od-muted-2": "#b0a89a",
  "od-accent": "#e8897a",
  "od-accent-2": "#ffa693"
};

export const tokens = { light, dark };

/**
 * The `var()` reference for a token, for building inline styles or SVG.
 * @param {string} name token name without `--`
 * @param {string} [fallback]
 * @returns {string}
 */
export function cssVar(name, fallback) {
  return fallback === undefined ? `var(--${name})` : `var(--${name}, ${fallback})`;
}

export default tokens;
