// GENERATED by scripts/generate-tokens.mjs from css/tokens.css — do not edit.
export declare const light: Record<string, string>;
export declare const dark: Record<string, string>;
export declare const tokens: { light: Record<string, string>; dark: Record<string, string> };
export declare function cssVar(name: string, fallback?: string): string;
declare const _default: typeof tokens;
export default _default;
