// GENERATED by scripts/generate-tokens.mjs from css/tokens.css — do not edit.
// Run `npm run tokens` after changing tokens.css.
//
// Keys are the CSS custom property name without the leading `--`, verbatim, so
// what you read here is greppable against the stylesheet.

/** @type {Record<string, string>} */
export const light = {
  "paper": "#fbf9fb",
  "paper-2": "#f4eef4",
  "ink": "#1a1023",
  "ink-2": "#4c3f58",
  "ink-3": "#74697e",
  "magenta": "#d6117e",
  "magenta-deep": "#9c0b5c",
  "link-hover": "#cc0f74",
  "violet": "#6e3fa3",
  "line": "#e6dde8",
  "card": "#ffffff",
  "dark-panel": "#1a1023",
  "font-display": "\"Fraunces\", Georgia, serif",
  "font-body": "\"Public Sans\", system-ui, sans-serif",
  "font-mono": "\"JetBrains Mono\", ui-monospace, monospace",
  "w-max": "1240px",
  "w-prose": "720px",
  "radius": "10px",
  "ease-out": "cubic-bezier(0.22, 1, 0.36, 1)",
  "ease-in-out": "cubic-bezier(0.65, 0, 0.35, 1)",
  "dur-1": "0.16s",
  "dur-2": "0.28s",
  "dur-3": "0.62s",
  "magenta-btn": "#cc0f74",
  "magenta-btn-hover": "#9c0b5c",
  "od-heading": "#ffffff",
  "od-fg": "#efe8f2",
  "od-fg-2": "#d9cce2",
  "od-fg-3": "#c9bcd4",
  "od-muted": "#94869f",
  "od-muted-2": "#a795b5",
  "od-accent": "#ff8ecb",
  "od-accent-2": "#ffb3da"
};

/** @type {Record<string, string>} */
export const dark = {
  "paper": "#16101c",
  "paper-2": "#211a29",
  "ink": "#efe8f4",
  "ink-2": "#c6b8d2",
  "ink-3": "#94869f",
  "magenta": "#e5308f",
  "magenta-deep": "#ff7ec0",
  "link-hover": "#ffb3da",
  "violet": "#6e3fa3",
  "line": "#362b42",
  "card": "#1e1626",
  "dark-panel": "#0f0a14",
  "font-display": "\"Fraunces\", Georgia, serif",
  "font-body": "\"Public Sans\", system-ui, sans-serif",
  "font-mono": "\"JetBrains Mono\", ui-monospace, monospace",
  "w-max": "1240px",
  "w-prose": "720px",
  "radius": "10px",
  "ease-out": "cubic-bezier(0.22, 1, 0.36, 1)",
  "ease-in-out": "cubic-bezier(0.65, 0, 0.35, 1)",
  "dur-1": "0.16s",
  "dur-2": "0.28s",
  "dur-3": "0.62s",
  "magenta-btn": "#cc0f74",
  "magenta-btn-hover": "#9c0b5c",
  "od-heading": "#ffffff",
  "od-fg": "#efe8f2",
  "od-fg-2": "#d9cce2",
  "od-fg-3": "#c9bcd4",
  "od-muted": "#94869f",
  "od-muted-2": "#a795b5",
  "od-accent": "#ff8ecb",
  "od-accent-2": "#ffb3da"
};

export const tokens = { light, dark };

/**
 * The `var()` reference for a token, for building inline styles or SVG.
 * @param {string} name token name without `--`
 * @param {string} [fallback]
 * @returns {string}
 */
export function cssVar(name, fallback) {
  return fallback === undefined ? `var(--${name})` : `var(--${name}, ${fallback})`;
}

export default tokens;
