/**
 * Generate the JS/JSON token exports from css/tokens.css.
 *
 * tokens.css is the single source of truth. Anything that needs the values
 * outside a stylesheet — OG image generation, SVG badges, HTML emails, a Tauri
 * app, a Worker rendering inline SVG charts — reads the generated output rather
 * than a second hand-maintained copy. Recreating that copy by hand is precisely
 * the failure this package exists to prevent.
 *
 *   node scripts/generate-tokens.mjs [--check]
 *
 * `--check` regenerates into memory and exits non-zero if the committed files
 * differ, so CI catches a tokens.css edit that never reached the JS side.
 *
 * It also asserts an invariant the CSS cannot express: the dark values appear
 * twice in tokens.css — once under `prefers-color-scheme` and once under the
 * manual `[data-theme="dark"]` override — and those two blocks MUST agree. If
 * they drift, the manual theme toggle starts rendering different colours from
 * the system preference, which is close to impossible to spot by eye.
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");

/** Pull `--name: value;` pairs out of a CSS block, ignoring comments. */
function declarations(block) {
  const out = {};
  const withoutComments = block.replace(/\/\*[\s\S]*?\*\//g, "");
  for (const [, name, value] of withoutComments.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) {
    out[name.slice(2)] = value.trim().replace(/\s+/g, " ");
  }
  return out;
}

/** Extract the body of the first block whose selector line matches `pattern`. */
function block(css, pattern) {
  const start = css.search(pattern);
  if (start === -1) throw new Error(`tokens.css: no block matching ${pattern}`);
  const open = css.indexOf("{", start);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}" && --depth === 0) return css.slice(open + 1, i);
  }
  throw new Error(`tokens.css: unbalanced braces after ${pattern}`);
}

const css = await readFile(join(root, "css/tokens.css"), "utf8");

const light = declarations(block(css, /^:root \{/m));
// Inside the media query the selector is `:root:not([data-theme="light"])`.
const darkAuto = declarations(block(css, /:root:not\(\[data-theme="light"\]\)/));
const darkManual = declarations(block(css, /^:root\[data-theme="dark"\]/m));

// The invariant. Compare only the keys the dark blocks actually declare.
const mismatches = [];
for (const key of new Set([...Object.keys(darkAuto), ...Object.keys(darkManual)])) {
  if (darkAuto[key] !== darkManual[key]) {
    mismatches.push(`  --${key}: system=${darkAuto[key] ?? "(absent)"} manual=${darkManual[key] ?? "(absent)"}`);
  }
}
if (mismatches.length > 0) {
  process.stderr.write(
    [
      "tokens.css: the two dark blocks disagree.",
      "",
      "The `prefers-color-scheme` block and the `[data-theme=\"dark\"]` manual",
      "override must declare identical values, or forcing dark mode renders",
      "different colours from inheriting it from the OS.",
      "",
      ...mismatches,
      "",
    ].join("\n"),
  );
  process.exit(1);
}

// Dark is a partial override: fall back to the light value for anything the dark
// blocks do not restate (fonts, widths, motion, the on-dark palette).
const dark = { ...light, ...darkManual };

const json = `${JSON.stringify({ light, dark }, null, 2)}\n`;

const js = `// GENERATED by scripts/generate-tokens.mjs from css/tokens.css — do not edit.
// Run \`npm run tokens\` after changing tokens.css.
//
// Keys are the CSS custom property name without the leading \`--\`, verbatim, so
// what you read here is greppable against the stylesheet.

/** @type {Record<string, string>} */
export const light = ${JSON.stringify(light, null, 2)};

/** @type {Record<string, string>} */
export const dark = ${JSON.stringify(dark, null, 2)};

export const tokens = { light, dark };

/**
 * The \`var()\` reference for a token, for building inline styles or SVG.
 * @param {string} name token name without \`--\`
 * @param {string} [fallback]
 * @returns {string}
 */
export function cssVar(name, fallback) {
  return fallback === undefined ? \`var(--\${name})\` : \`var(--\${name}, \${fallback})\`;
}

export default tokens;
`;

const dts = `// GENERATED by scripts/generate-tokens.mjs from css/tokens.css — do not edit.
export declare const light: Record<string, string>;
export declare const dark: Record<string, string>;
export declare const tokens: { light: Record<string, string>; dark: Record<string, string> };
export declare function cssVar(name: string, fallback?: string): string;
declare const _default: typeof tokens;
export default _default;
`;

const files = [
  ["tokens/tokens.json", json],
  ["tokens/index.js", js],
  ["tokens/index.d.ts", dts],
];

if (check) {
  const stale = [];
  for (const [path, want] of files) {
    const got = await readFile(join(root, path), "utf8").catch(() => null);
    if (got !== want) stale.push(path);
  }
  if (stale.length > 0) {
    process.stderr.write(
      `tokens.css has changed but these are stale:\n${stale.map((p) => `  ${p}`).join("\n")}\n\nRun: npm run tokens\n`,
    );
    process.exit(1);
  }
  process.stderr.write(`tokens up to date (${Object.keys(light).length} tokens)\n`);
} else {
  for (const [path, content] of files) await writeFile(join(root, path), content, "utf8");
  process.stderr.write(
    `wrote ${files.length} files — ${Object.keys(light).length} tokens, ${Object.keys(darkManual).length} overridden in dark\n`,
  );
}
